F1/F1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.contrib.auth import views as auth_views
from .views import UserCreateView, nothing_here, UserCreateSelection, CompanyCreateView, get_notifications

urlpatterns = [
    path('favicon.ico', RedirectView.as_view(url='/static/images/icons/favicon.ico')),
    path('admin/', admin.site.urls),
    path('nothing_here/', nothing_here, name='nothing_here'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register/', UserCreateSelection, name='register_selection'),
    path('register/utente/', UserCreateView.as_view(), name='register_user'),
    path('register/gestore/', CompanyCreateView.as_view(), name='register_company'),
    path('', include('media.urls')),
    path('', include('info.urls')),
    path('', include('store.urls')),
    path('query/notifications/', get_notifications, name='get_notifications'),
]

F1/info/urls.py
from .models import *
from django.urls import path
from info.views import follow, unfollow
from info.views import SessioniView, CircuitiView, ScuderieView, RisultatoSessioneView, TeamView, PilotaView, CircuitoView

app_name = 'info'

urlpatterns = [
    path('sessioni/', SessioniView.as_view(), name='sessioni'),
    path('sessioni/<pk>/<tipo_sessione>/', RisultatoSessioneView.as_view(), name='risultato_sessione'),
    path('circuiti/', CircuitiView.as_view(), name='circuiti'),
    path('circuiti/<pk>/', CircuitoView.as_view(), name='circuito'),
    path('scuderie/', ScuderieView.as_view(), name='scuderie' ),
    path('scuderie/team/<pk>/', TeamView.as_view(), name='team'),
    path('scuderie/team/<pk>/follow/', follow, name='follow'),
    path('scuderie/team/<pk>/unfollow/', unfollow, name='unfollow'),
    path('pilota/<pk>/', PilotaView.as_view(), name='pilota'),
]

F1/store/urls.py
from django.urls import path
from store.views import UserProfile, UtenteProfileDataChangeViewUpdate, StoreView, ProductView, CartView, GestoreProfileDataChangeViewUpdate, CreateTicketTypeView, CreateTicketInstanceView

app_name = 'store'

urlpatterns = [
    path('profile/', UserProfile, name='profile'),
    path('profile/modify_utente/<int:pk>/', UtenteProfileDataChangeViewUpdate.as_view(), name='modify_utente_update'),
    path('profile/modify_gestore/<int:pk>/', GestoreProfileDataChangeViewUpdate.as_view(), name='modify_gestore_update'),
    path('profile/create_ticket_type/', CreateTicketTypeView.as_view(), name='create_ticket_type'),
    path('profile/create_ticket_instance/', CreateTicketInstanceView.as_view(), name='create_ticket_instance'),
    path('store/', StoreView.as_view(), name='store'),
    path('store/product/<int:pk>/', ProductView.as_view(), name='product'),
    path('cart/', CartView.as_view(), name='cart'),
]

F1/store/models.py
from django.db import models
from F1.validators import valida_non_negativi, valida_iban, valida_carta_credito, valida_cvv
from django.contrib.auth.models import User
from info.models import Circuito, Scuderia
from media.models import PortaleF1
from datetime import date
from django_countries.fields import CountryField


class Gestore_Circuito(models.Model):
    sito_web = models.CharField(max_length=100)
    indirizzo = models.CharField(max_length=50)
    telefono = models.CharField(max_length=25)
    iban = models.CharField(max_length=34, validators=[valida_iban])
    notifiche = models.BooleanField(null=False, default=False)

    # Un gestore di un circuito gestisce uno e un solo circuito e un circuito è gestito da uno e un solo gestore
    gestione_circuito = models.OneToOneField(Circuito, on_delete=models.PROTECT, null=True, blank=True)

    # Connette i gestori dei circuiti con la table User
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    # Al portale di F1 appartengono da 0 a N gestori di un circuito, e ogni gestore appartiene al portale di F1
    portale_f1 = models.ForeignKey(PortaleF1, on_delete=models.PROTECT, null=True, blank=True)

    class Meta:
        verbose_name_plural = 'Gestori circuiti'


class Utente(models.Model):
    
    SESSO_CHOICES = [
        ('M', 'Maschio'),
        ('F', 'Femmina')
    ]

    indirizzo = models.CharField(max_length=50, null=True, default=None, blank=True)
    data_nascita = models.DateField(null=True, blank=True, default=date.today)
    sesso = models.CharField(max_length=10, choices=SESSO_CHOICES, null=True, blank=True)
    paese = CountryField(null=True, blank=True, default=None)
    telefono = models.CharField(max_length=25, null=True, default=None, blank=True)
    immagine_profilo = models.CharField(max_length=100, null=True, default='/static/users/default/default.jpg', blank=True)
    carta_credito = models.CharField(max_length=19, validators=[valida_carta_credito], null=True, default=None, blank=True)
    cvv = models.CharField(max_length=3, validators=[valida_cvv], null=True, default=None, blank=True)
    scadenza_carta = models.DateField(null=True, default=date.today, blank=True)
    notifiche = models.BooleanField(null=False, default=False)
    follow = models.ManyToManyField(Scuderia, blank=True, default=None)

    # Connette gli utenti con la table User
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    # Al portale di F1 appartengono da 0 a N utenti, e ogni utente appartiene al portale di F1
    portale_f1 = models.ForeignKey(PortaleF1, on_delete=models.PROTECT, null=True, blank=True)

    class Meta:
        verbose_name_plural = 'Utenti'


class Ordine(models.Model):
    data = models.DateField(null=False, blank=False, default=date.today)
    prezzo = models.FloatField(validators=[valida_non_negativi], default=0.00)
    biglietto_digitale = models.CharField(max_length=100, null=False, default='', blank=False)

    # Un ordine si riferisce a uno e un solo utente
    utente = models.ForeignKey(Utente, on_delete=models.PROTECT, null=False, blank=False)

    class Meta:
        verbose_name_plural = 'Ordini'   


class Notifica(models.Model):
    descrizione = models.CharField(max_length=100)
    data = models.DateField(null=False, blank=False, default=date.today)

    # Una notifica si riferisce al più a un ordine
    ordine = models.ForeignKey(Ordine, on_delete=models.CASCADE, null=True, blank=True)

    class Meta:
        verbose_name_plural = 'Notifiche'


class TipologiaBiglietto(models.Model):
    settore = models.CharField(max_length=50)
    data_evento = models.DateField(null=False, blank=False, default=date.today)
    prezzo = models.FloatField(validators=[valida_non_negativi], default=0.00)

    # Una precisa tipologia di biglietto viene pubblicata nello store da uno e un solo gestore di un circuito
    gestore_circuito = models.ForeignKey(Gestore_Circuito, on_delete=models.PROTECT, null=False, blank=False)

    def get_istanza_biglietto_amount(self):
        '''Restituisce il numero di istanze di biglietti di una precisa tipologia di biglietto'''
        istanze_biglietti = self.istanzabiglietto_set.filter(ordine=None)
        return istanze_biglietti.count()

    class Meta:
        verbose_name_plural = 'Tipologia Biglietti'


class IstanzaBiglietto(models.Model):
    numero_posto = models.PositiveIntegerField()

    # Se una precisa istanza di biglietto è stata acquistata è contenuta in al più un ordine
    # Se non è stato acquistata non è contenuta in nessun ordine
    ordine = models.ForeignKey(Ordine, on_delete=models.PROTECT, null=True, blank=True, default=None)

    # Ogni istanza di un biglietto si riferisce a una e una sola tipologia di biglietto
    tipologia_biglietto = models.ForeignKey(TipologiaBiglietto, on_delete=models.PROTECT, blank=False, default=None, null=True)

    class Meta:
        verbose_name_plural = 'Istanza Biglietti'


class Carrello(models.Model):
    # Un preciso carrello è posseduto da uno e un solo utente
    # In caso di cancellazione dell'utente è necessario cancellare anche il carrello
    possedimento_carrello = models.OneToOneField(Utente, on_delete=models.CASCADE, default=None)

    # Un carrello può contenere da 0 a N istanze di biglietti
    istanze_biglietti = models.ManyToManyField(IstanzaBiglietto, blank=True)

    class Meta:
        verbose_name_plural = 'Carrelli'

F1/store/forms.py
from django import forms
from django_countries import countries


class UtenteProfileFormData(forms.Form):
    nome = forms.CharField(label='Nome', required=False, max_length=100, help_text='Caratteri validi per il nome (a-z, A-Z)')
    cognome = forms.CharField(label='Cognome', required=False, max_length=100, help_text='Caratteri validi per il cognome (a-z, A-Z)')
    email = forms.CharField(label='Email', required=False, max_length=100, help_text='Formato valido email: user_name@domain_name.tld')
    indirizzo = forms.CharField(label='Indirizzo', required=False, max_length=50)
    data_nascita = forms.DateField(label='Data di nascita', required=False, widget=forms.DateInput(attrs={'type': 'date'}), help_text='La data di nascita non può essere nel futuro')
    sesso_choices = [('M', 'Maschio'), ('F', 'Femmina')]
    sesso = forms.ChoiceField(label='Sesso', choices=sesso_choices, required=False, initial="F")
    paese = forms.ChoiceField(label='Paese', choices=countries, required=False, initial='IT')
    telefono = forms.CharField(label='Telefono', required=False, max_length=25, help_text='Formati telefonici validi (0-9): +391234567890, 1234567890')
    carta_credito = forms.CharField(label='Carta di credito', required=False, max_length=19, help_text='Formato valido carta di credito (0-9): 1234123412341234')
    cvv = forms.CharField(label='CVV', required=False, max_length=3, help_text='Formato valido CVV (0-9): 123')
    scadenza_carta = forms.DateField(label='Scadenza carta', required=False, widget=forms.DateInput(attrs={'type': 'date'}), help_text='La data di scadenza non può essere nel passato')
    
    def __init__(self, *args, **kwargs):
        super(UtenteProfileFormData, self).__init__(*args, **kwargs)
        self.add_tooltips()

    def add_tooltips(self):
        for field_name, field in self.fields.items():
            field.widget.attrs['title'] = field.label
        

class TicketForm(forms.Form):
    
    istanze_biglietti = forms.ChoiceField(label='', choices=[], required=True, initial="1")
    
    def __init__(self, *args, **kwargs):
        super(TicketForm, self).__init__(*args, **kwargs)
        self.add_tooltips()

    def add_tooltips(self):
        for field_name, field in self.fields.items():
            field.widget.attrs['title'] = field.label


class GestoreProfileFormData(forms.Form):
    indirizzo = forms.CharField(label='Indirizzo', required=False, max_length=50)
    telefono = forms.CharField(label='Telefono', required=False, max_length=25, help_text='Formati telefonici validi (0-9): +391234567890, 1234567890')
    sito_web = forms.CharField(label='Sito web', required=False, max_length=100, help_text='Formato valido sito web: www.example.com')
    iban = forms.CharField(label='IBAN', required=False, max_length=27, help_text='Formato valido IBAN (0-9): IT00A1234567890123456789012')
    email = forms.EmailField(label='Email', required=False, max_length=100, help_text='Formato valido email: user_name@domain_name.tld')

    def __init__(self, *args, **kwargs):
        super(GestoreProfileFormData, self).__init__(*args, **kwargs)
        self.add_tooltips()
    
    def add_tooltips(self):
        for field_name, field in self.fields.items():
            field.widget.attrs['title'] = field.label


class CreateTicketTypeForm(forms.Form):
    settore = forms.CharField(label='Settore', required=True, max_length=100, help_text='Caratteri validi per il settore (0-9)')
    data_evento = forms.DateField(label='Data evento', required=True, widget=forms.DateInput(attrs={'type': 'date'}), help_text='La data dell\'evento non può essere nel passato')
    prezzo = forms.FloatField(label='Prezzo', required=True, help_text='Il prezzo non può essere negativo')

    def __init__(self, *args, **kwargs):
        super(CreateTicketTypeForm, self).__init__(*args, **kwargs)
        self.add_tooltips()

    def add_tooltips(self):
        for field_name, field in self.fields.items():
            field.widget.attrs['title'] = field.label


class CreateTicketInstanceForm(forms.Form):
    tipologia_biglietto = forms.ChoiceField(label='Tipologia biglietto', choices=[], required=True, initial="1")
    numero_posto = forms.IntegerField(label='Numero posto', required=True, help_text='Il numero del posto non può essere negativo')

F1/templates/store/store.html
{% extends 'base.html' %}
{% load crispy_forms_tags %} 
{% load static %}

{% block head %} 

	<link rel="stylesheet" type="text/css" href="{%static 'css/style.css'%}">
    <link rel="stylesheet" type="text/css" href="{%static 'css/style_store.css'%}">

{% endblock %}

{% block title %}F1 - Store{% endblock %}

{% block content %}

<div class="store-container mt-4 ml-4 mr-4 mb-4 text-white">
    <div class="query-page-selector-container" align="right">
        <h1 class="ml-4 mt-2 f1-font-bold mt-2">Store</h1> 
        <div class="query-page-selector-container mt-2" align="right">
            
            <div class="dropdown f1-font-regular">
                <button class="mt-2 mr-4">Filtra articoli ▼</button>
                <div class="dropdown-content top-dropdown-content" align="left">         
                    <a href="{% url 'store:store' %}?filter=price_asc">Prezzo ▲</a>
                    <a href="{% url 'store:store' %}?filter=price_desc">Prezzo ▼</a>
                    <a href="{% url 'store:store' %}?filter=date_asc">Data ▲</a>
                    <a href="{% url 'store:store' %}?filter=date_desc">Data ▼</a>
                </div>
            </div>

            {% if tipologie_biglietti.has_previous %}
                <a href="{% url 'store:store' %}?page={{ request.GET.page|add:-1 }}{% if filter %}&filter={{filter}}{% endif %}">        
                    <button class="mr-2 mt-2 f1-font-regular">Precedente</button>  
                </a>
            {% else %}
                <button class="mr-2 mt-2 f1-font-regular disabled-button">Precedente</button> 
            {% endif %}

            <h2 class="ml-auto mt-2 mr-2 f1-font-regular">[ </h2>
            {% if request.GET.page %}
                <h2 class="ml-auto mt-2 mr-2 f1-font-regular">{{ request.GET.page }}</h2>
            {% else %}
                <h2 class="ml-auto mt-2 mr-2 f1-font-regular">1</h2>
            {% endif %}
            <h2 class="ml-auto mt-2 mr-2 f1-font-regular"> ]</h2>
            
            {% if tipologie_biglietti.has_next %}
                <a href="{% url 'store:store' %}?page={% if request.GET.page %}{{ request.GET.page|add:1 }}{% else %}2{% endif %}{% if filter %}&filter={{filter}}{% endif %}">
                    <button class="ml-auto mr-4 mt-2 f1-font-regular">Prossimo</button>    
                </a>
            {% else %}
                <button class="ml-auto mr-4 mt-2 f1-font-regular disabled-button">Prossimo</button> 
            {% endif %}

        </div>
    </div>
    <hr class="solid ml-4 mr-4 divisore"></hr>

    <div class="container-fluid main_container text-white">
        <div class="row">
            {% for tipologia_biglietto in tipologie_biglietti %}
                
                {% with forloop_id=forloop.counter %}
                <div class="col-sm-3 mb-2 {% if tipologia_biglietto.amount <= 0 %}not-available{% endif %}" style="height: 43vh; padding: 10px;" style="display: block;">
                    
                    <div class="product-item mx-auto  card-product-preview f1-font-regular " style="">
                       
                        <a href="{% url 'info:circuito' pk=tipologia_biglietto.gestore_circuito.gestione_circuito.id %}">
                            <img class="mx-auto product-preview-image product-info" src="{{tipologia_biglietto.gestore_circuito.gestione_circuito.preview}}">
                        </a>
                        <div style="display: flex;">
                            <a href="{% url 'store:product' pk=tipologia_biglietto.id %}" class="f1-font-bold mx-auto product-info">
                                <p>{{ tipologia_biglietto.gestore_circuito.gestione_circuito.nome }} - Settore {{ tipologia_biglietto.settore }}</p>
                            </a>
                        </div>

                        <div class="row">
                            <p class="col-6" style="text-align: left;  left: 15px;">{{tipologia_biglietto.amount}} rimanenti</p>

                            <p class="col-6" style="text-align: right;  right: 15px;">{{ tipologia_biglietto.prezzo }} €</p>
                        </div>
                                    
                        <div class="row">
                            
                            <div class="col-6" style="">
                                {% if tipologia_biglietto.amount > 0 %}
                                <div class="dropdown f1-font-regular ml-2" >
                                    <button id=button{{ forloop_id }} class="dropdown-btn">Disponibilità ▲</button>
                                    <div class="dropdown-content bottom-dropdown-content">

                                        {% for istanza_biglietto in istanze_biglietti %}
                                            {% if istanza_biglietto.tipologia_biglietto == tipologia_biglietto %}
                                                <a class="ticket">Posto {{istanza_biglietto.numero_posto}}</a>
                                            {% endif %}
                                        {% endfor %}
                                        
                                    </div>
                                </div>
                                {% endif %}
                            </div>


                            <div class="col-6" style="text-align: right;">
                                <a href="{% url 'store:product' pk=tipologia_biglietto.id %}" class=" f1-font-regular mx-auto">
                                    <button class="f1-font-regular mr-2" style="width: 150px; height:40px; margin-bottom: 10px;">Vai al prodotto</button>
                                </a>
                            </div>
                        </div>

                    </div>

                </div>
                {% endwith %}
            {% endfor %}
            
        </div>
    
    </div>
</div>
    
{% endblock %}

F1/templates/store/user_profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %} 
{% load static %}

{% block head %} 

	<link rel="stylesheet" type="text/css" href="{%static 'css/style_profilo.css'%}">

{% endblock %}

{% block title %} F1 - Profilo {{ form.user_group_name }} {% endblock %} 

{% block header1 %}
	<h1>Pagina del profilo di {{ user.username }}</h1>
{% endblock %}

{% block content %} 

	{% if utente %}

		{% include 'store/user_profile_modal.html' %}

		<!-- Dati utente -->
		<div class="profilo-container text-white f1-font-bold mt-2 ml-2 mr-2">
			<div id="profile" class="background-profile-darker" style="overflow-x: hidden; {% if user.gestore_circuito %}overflow-y: hidden;{% endif %}">
				<div class="row" >

					<div class="col-lg-4 background-profile" {% if user.gestore_circuito %}style="height: 90vh;"{% endif %}>
						<div class="card-body text-center mt-4 ml-4">
							<div id="profile-image-container" class="mx-auto">
								{% if user.gestore_circuito %}
									<img src="{% static 'companies/default.png' %}" alt="avatar" class="img-fluid">
								{% elif user.utente %}	
									<img id="profile-image" src="{{ utente.immagine_profilo }}" alt="avatar" class="img-fluid">
								{% endif %}
							</div>
							<script src="{%static 'js/user_profile_image_upload_modal.js'%}"></script>
					
							<h6 class="my-3">{{ user.username }}</h6>

							<br>
							<p class="text-muted mb-0">Ultimo accesso {{ user.last_login }}</p>

							<div id="modifica-profilo" class="d-flex justify-content-center mt-4">	
								{% if user.gestore_circuito %}
									<a href="{% url 'store:modify_gestore_update' pk=request.user.gestore_circuito.pk %}">
										<button type="button" class="profile-button">Modifica profilo</button>
									</a>	
								{% elif user.utente %}
									<a href="{% url 'store:modify_utente_update' pk=request.user.utente.pk %}">
										<button type="button" class="profile-button">Modifica profilo</button>
									</a>
								{% endif %}
							</div>
							{% if user.gestore_circuito %}
								<div id="crea-tipologia-articolo" class="d-flex justify-content-center mt-4">	
									<a href="{% url 'store:create_ticket_type' %}">
										<button type="button" class="profile-button" style="height:150px;">Crea tipologia biglietto</button>
									</a>
								</div>
								<div id="crea-istanza-articolo" class="d-flex justify-content-center mt-4" >
									<a href="{% url 'store:create_ticket_instance' %}">
										<button type="button" class="profile-button" style="height:150px;">Crea istanza biglietto</button>
									</a>
								</div>
								<div class="d-flex justify-content-center mt-4" >

									<button type="button" class="profile-button" style="height:150px;" onclick="openChartModal()">Statistiche vendite</button>

								</div>

								{% include 'store/gestore_chart_modal.html' %}
							{% endif %}
						</div>
					</div>

					{% if user.gestore_circuito %}
						<div id="user-data" class="col-lg-8 background-profile-darker" >
							<div class="card-body">
								<div class="row">
									<div class="col-sm-3">
										<p class="mb-0">Indirizzo</p>
									</div>
									<div class="col-sm-8">
										<p class="text-muted mb-0" >{{ user.gestore_circuito.indirizzo }}</p>
									</div>
								</div>
							</div>
							<br>

							<div class="card-body">
								<div class="row">
									<div class="col-sm-3">
										<p class="mb-0">Telefono</p>
									</div>
									<div class="col-sm-8">
										<p class="text-muted mb-0" >{{ user.gestore_circuito.telefono }}</p>
									</div>
								</div>
							</div>
							<br>

							<div class="card-body">
								<div class="row">
									<div class="col-sm-3">
										<p class="mb-0">Email</p>
									</div>
									<div class="col-sm-8">
										<p class="text-muted mb-0" >{{ user.email }}</p>
									</div>
								</div>
							</div>
							<br>

							<div class="card-body">
								<div class="row">
									<div class="col-sm-3">
										<p class="mb-0">Sito Web</p>
									</div>
									<div class="col-sm-8">
										<p class="text-muted mb-0" >{{ user.gestore_circuito.sito_web }}</p>
									</div>
								</div>
							</div>
							<br>

							<div class="card-body">
								<div class="row">
									<div class="col-sm-3">
										<p class="mb-0">IBAN</p>
									</div>
									<div class="col-sm-8">
										<p class="text-muted mb-0" style="font-size: 14px;">{{ user.gestore_circuito.iban }}</p>
									</div>
								</div>
							</div>
							<br>

							<div class="card-body">
								<div class="row">
									<div class="col-sm-3">
										<p class="mb-0">Circuito</p>
									</div>
									<div class="col-sm-8">
										<p class="text-muted mb-0" style="font-size: 14px;">{{ circuito.nome }}</p>
									</div>
								</div>
							</div>
							<br>
							
							

						</div>
					{% else %}
						<div id="user-data" class="col-lg-8 background-profile-darker">
							<div class="card-body">
								<div class="row">
									<div class="col-sm-4">
										<p class="mb-0">Nome</p>
									</div>
									<div class="col-sm-8">
										<p class="text-muted mb-0" >{{ user.first_name }}</p>
									</div>
								</div>
							</div>
							<br>

							<div class="card-body">
								<div class="row">
									<div class="col-sm-4">
										<p class="mb-0">Cognome</p>
									</div>
									<div class="col-sm-8">
										<p class="text-muted mb-0" >{{ user.last_name }}</p>
									</div>
								</div>
							</div>
							<br>

							<div class="card-body">
								<div class="row">
									<div class="col-sm-4">
										<p class="mb-0">Indirizzo Email</p>
									</div>
									<div class="col-sm-8">
										<p class="text-muted mb-0">{{ user.email }}</p>
									</div>
								</div>
							</div>
							<br>

							<div class="card-body">
								<div class="row">
									<div class="col-sm-4">
										<p class="mb-0">Data di nascita</p>
									</div>
									<div class="col-sm-8">
										<p class="text-muted mb-0">{{ utente.data_nascita }}</p>
									</div>
								</div>
							</div>
							<br>

							<div class="card-body">
								<div class="row">
									<div class="col-sm-4">
										<p class="mb-0">Sesso</p>
									</div>
									<div class="col-sm-8">
										<p class="text-muted mb-0">{{ utente.get_sesso_display }}</p>
									</div>
								</div>
							</div>
							<br>

							<div class="card-body">
								<div class="row">
									<div class="col-sm-4">
										<p class="mb-0">Paese</p>
									</div>
									<div class="col-sm-8">
										<p class="text-muted mb-0">{{ utente.paese.name }}</p>
									</div>
								</div>
							</div>
							<br>

							<div class="card-body">
								<div class="row">
									<div class="col-sm-4">
										<p class="mb-0">Telefono</p>
									</div>
									<div class="col-sm-8">
										<p class="text-muted mb-0">{{ utente.telefono }}</p>
									</div>
								</div>
							</div>
							<br>

							<div class="card-body">
								<div class="row">
									<div class="col-sm-4">
										<p class="mb-0">Carta di credito</p>
									</div>
									<div class="col-sm-8">
										<p class="text-muted mb-0">{{ utente.carta_credito }}</p>
									</div>
								</div>
							</div>
							<br>

							<div class="card-body">
								<div class="row">
									<div class="col-sm-4">
										<p class="mb-0">Scadenza carta</p>
									</div>
									<div class="col-sm-8">
										<p class="text-muted mb-0">{{ utente.scadenza_carta }}</p>
									</div>
								</div>
							</div>
							<br>

							<div class="card-body">
								<div class="row">
									<div class="col-sm-4">
										<p class="mb-0">CVV</p>
									</div>
									<div class="col-sm-8">
										<p class="text-muted mb-0">{% if utente.cvv %}***{% endif %}</p>
									</div>
								</div>
							</div>
							
						</div>
					{% endif %}

				</div>

				
			</div>
		
			<!-- Ordini -->
			<div class="background-profile-darker card" style="overflow-y: auto;">
				<h2 class="mx-auto f1-font-bold mt-2">I tuoi ordini</h2>
				<table class="order-table mt-3 ml-2 mr-2">
					<tr>
						<th class="order-cell f1-font-bold">Id ordine</th>
						<th class="order-cell f1-font-bold">Data acquisto</th>
						<th class="order-cell f1-font-bold">Prezzo</th>
						{% if user.utente %}
							<th class="order-cell f1-font-bold">Download</th>
						{% elif user.gestore_circuito %}
							<th class="order-cell f1-font-bold">Acquirente</th>
						{% endif %}
					</tr>
					{% if user.utente %}
						{% for ordine in ordini_utente %}
							<tr>
								<th class="order-cell f1-font-regular">Ordine {{ ordine.id }}</td>
								<th class="order-cell f1-font-regular">{{ ordine.data }}</td>
								<th class="order-cell f1-font-regular">{{ ordine.prezzo|floatformat:2 }} €</td>
								{% if user.utente %}
									<th class="order-cell f1-font-bold">
										<a target="_blank" href="/static/tickets/Ordine_{{ordine.id}}_{{user.first_name}}_{{user.last_name}}.pdf" style="color: white;">
											<i class="fa fa-cloud-download" style=""></i>
										<a>
									</th>
								{% endif %}
							</tr>
						{% endfor %}
					{% elif user.gestore_circuito %}
						{% for ordine in ordini_circuito %}
							<tr>
								<th class="order-cell f1-font-regular">Ordine {{ ordine.id }}</td>
								<th class="order-cell f1-font-regular">{{ ordine.data }}</td>
								<th class="order-cell f1-font-regular">{{ ordine.prezzo|floatformat:2 }} €</td>
								<th class="order-cell f1-font-regular">{{ ordine.utente.user.username }}</td>
							</tr>
						{% endfor %}
					{% endif %}

				</table>
			</div>
		</div>	
	{% endif %}
	
{% endblock %}

{% block footer %} {% endblock %}