F1/F1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.contrib.auth import views as auth_views
from .views import UserCreateView, nothing_here, UserCreateSelection, CompanyCreateView, get_notifications

urlpatterns = [
    path('favicon.ico', RedirectView.as_view(url='/static/images/icons/favicon.ico')),
    path('admin/', admin.site.urls),
    path('nothing_here/', nothing_here, name='nothing_here'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register/', UserCreateSelection, name='register_selection'),
    path('register/utente/', UserCreateView.as_view(), name='register_user'),
    path('register/gestore/', CompanyCreateView.as_view(), name='register_company'),
    path('', include('media.urls')),
    path('', include('info.urls')),
    path('', include('store.urls')),
    path('query/notifications/', get_notifications, name='get_notifications'),
]

F1/info/urls.py
from .models import *
from django.urls import path
from info.views import follow, unfollow
from info.views import SessioniView, CircuitiView, ScuderieView, RisultatoSessioneView, TeamView, PilotaView, CircuitoView

app_name = 'info'

urlpatterns = [
    path('sessioni/', SessioniView.as_view(), name='sessioni'),
    path('sessioni/<pk>/<tipo_sessione>/', RisultatoSessioneView.as_view(), name='risultato_sessione'),
    path('circuiti/', CircuitiView.as_view(), name='circuiti'),
    path('circuiti/<pk>/', CircuitoView.as_view(), name='circuito'),
    path('scuderie/', ScuderieView.as_view(), name='scuderie' ),
    path('scuderie/team/<pk>/', TeamView.as_view(), name='team'),
    path('scuderie/team/<pk>/follow/', follow, name='follow'),
    path('scuderie/team/<pk>/unfollow/', unfollow, name='unfollow'),
    path('pilota/<pk>/', PilotaView.as_view(), name='pilota'),
]

F1/media/urls.py
from . import views
from .models import *
from django.urls import path
from media.views import HomePageView, HighlightPageView, VideoHighlightPageView

app_name = 'media'

urlpatterns = [
    path('', HomePageView.as_view(), name='homepage'),
    path('highlight/', HighlightPageView.as_view(), name='highlight'),
    path('highlight/<pk>/', VideoHighlightPageView.as_view(), name='highlight_video'),
]

F1/media/models.py
from django.db import models
from info.models import Scuderia


class PortaleF1(models.Model):
    
    class Meta:
        verbose_name_plural = 'PortaliF1'


class News(models.Model):
    titolo = models.CharField(max_length=100)
    data = models.DateField()
    tags = models.ManyToManyField(Scuderia, blank=True, default=None)
    link_news = models.CharField(max_length=250, default='')
    immagine = models.CharField(max_length=250, default='')

    # Il portale di F1 contiene da 0 a N news e una news è contenuta nel portale di F1
    portale_f1 = models.ForeignKey(PortaleF1, on_delete=models.PROTECT, null=True, blank=True)

    class Meta:
        verbose_name_plural = 'News'


class Highlight(models.Model):
    titolo = models.CharField(max_length=100)
    video = models.CharField(max_length=100)
    data = models.DateField()
    visualizzazioni = models.PositiveIntegerField(default=0)
    preview = models.CharField(max_length=200)

    # Il portale di F1 contiene da 0 a N highlight e un highlight è contenuto nel portale di F1
    portale_f1 = models.ForeignKey(PortaleF1, on_delete=models.PROTECT, null=True, blank=True)
    
    

F1/media/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit


class FormUtente(forms.Form):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.add_input(Submit('Login', 'Login'))

    nome = forms.CharField(label='nome')
    e_mail = forms.EmailField(label='e_mail')
    date_of_birth = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))

F1/media/views.py
from datetime import date
from store.models import Utente
from media.forms import FormUtente
from django.shortcuts import render
from django.shortcuts import redirect
from media.models import News, Highlight
from django.views.generic.list import ListView
from django.core.paginator import Paginator, EmptyPage
from info.models import Partecipazione, Sessione, Circuito


class HomePageView(ListView):
    '''Gestisce la homepage del sito fornendo:
    * Le informazioni relative all'ultima sessione disputata 
    * Gli ultimi articoli pubblicati (fino a un massimo di 10) nel caso l'utente non sia loggato o non sia un utente regolare o sia un utente regolare che non segue nessuna scuderia
    * Gli ultimi articoli pubblicati dalle scuderie seguite (fino a un massimo di 5) dall'utente nel caso l'utente sia loggato e sia un utente regolare che segue almeno una scuderia più altri 5 articoli pubblicati dalle scuderie non seguite dall'utente
    * Lista dei gran premi passati apposta a quella dei gran premi futuri'''
    model = News
    template_name = 'media/homepage.html' 

    def trova_data_ultima_sessione():
        ultima_partecipazione = Partecipazione.objects.order_by('-data').first()

        if ultima_partecipazione:
            ultima_sessione = ultima_partecipazione.data
            return ultima_sessione
        else:
            return None
    
    def trova_circuito_ultima_sessione():
        circuito_ultima_sessione = Partecipazione.objects.order_by('-data').first()
        if circuito_ultima_sessione:
            return circuito_ultima_sessione.circuito
        else:
            return None

    def get_context_data(self):
        context = super().get_context_data()

        data_ultima_sessione = HomePageView.trova_data_ultima_sessione()
        circuito_ultima_sessione = HomePageView.trova_circuito_ultima_sessione()
        user = self.request.user

        if data_ultima_sessione:
            partecipazioni = Partecipazione.objects.filter(data=data_ultima_sessione).order_by('posizione')
            sessione = Sessione.objects.filter(partecipazione__in=partecipazioni).first()
            circuito = Circuito.objects.filter(partecipazione__in=partecipazioni).first()

            context['partecipazioni'] = partecipazioni
            context['tipo_sessione'] = sessione.tipo
            context['nome_circuito'] = circuito.nome

        if circuito_ultima_sessione:
            context['circuito_ultima_sessione'] = circuito_ultima_sessione
        
        utente_regolare = False
        gestore_circuito = False

        if user.is_authenticated:
            try:
                if user.utente:
                    utente_regolare = True
                    gestore_circuito = False
                    utente = Utente.objects.get(user=user)
            except:
                utente_regolare = False
                gestore_circuito = True

        if utente_regolare and utente.follow:
            news = News.objects.filter(tags__in=utente.follow.all()).order_by('-data')[:5]

            unfollowed_news = News.objects.exclude(tags__in=utente.follow.all()).order_by('-data')[:5]

            context['news'] = news
            context['unfollowed_news'] = unfollowed_news

        else:
            news = News.objects.filter().order_by('-data')[:10]
            context['news'] = news

        circuiti_futuri = Circuito.objects.filter(data_evento__gte=date.today()).order_by('data_evento')

        circuiti_passati = Circuito.objects.exclude(pk__in=circuiti_futuri).order_by('-data_evento')

        circuiti = [circuito for circuito in circuiti_futuri]
        [circuiti.append(circuito) for circuito in circuiti_passati]

        context['circuiti'] = circuiti
        context['data'] = date.today()

        return context
    
    
class HighlightPageView(ListView):
    '''Gestisce la pagina degli highlight, mostrando un massimo di 6 highlight per pagina in ordine cronologico decrescente'''
    model = Highlight
    template_name = 'media/highlight.html' 
    NUM_VIDEO_PER_PAGINA = 6

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        highlights = Highlight.objects.all().order_by('-data')
        paginator = Paginator(highlights, HighlightPageView.NUM_VIDEO_PER_PAGINA)
        
        numero_pagina = self.request.GET.get('page', 1)

        context['nothing_here'] = False

        pagina = paginator.page(numero_pagina)

        context['highlights'] = pagina
        context['num_pages'] = str(paginator.num_pages)

        return context
    
    def get(self, request, *args, **kwargs):
        try:
            return super().get(request, *args, **kwargs)
        except EmptyPage:
            return redirect('nothing_here')
    

class VideoHighlightPageView(ListView):
    '''Gestisce la pagina di un singolo highlight fornendo le sue informazioni e incrementando il numero di visualizzazioni di 1 per ogni accesso alla pagina'''
    model = Highlight
    template_name = 'media/video_highlight.html'

    def get_context_data(self, **kwargs):
        try:
            context = super().get_context_data(**kwargs)
            pk = self.kwargs.get('pk')
            video = Highlight.objects.get(pk=pk)
            video.visualizzazioni += 1
            video.save()
            context['video'] = video
            return context
        except Highlight.DoesNotExist:
            return {}
        
    def get(self, request, *args, **kwargs):
        try:
            pk = self.kwargs.get('pk')
            video = Highlight.objects.get(pk=pk)
            return super().get(request, *args, **kwargs)
        except Exception:
            return redirect('nothing_here')

F1/templates/media/highlight.html
{% extends 'base.html' %}
{% load crispy_forms_tags %} 
{% load static %}

{% block head %} 

	<link rel="stylesheet" type="text/css" href="{%static 'css/style.css'%}">
    <link rel="stylesheet" type="text/css" href="{%static 'css/style_highlight.css'%}">

{% endblock %}

{% block title %} F1 - Highlight {% endblock %}

{% block content %}

    <div class="highlight-container mt-4 ml-4 mr-4 mb-4 text-white">
        <div class="query-page-selector-container" align="right">
            <h1 class="ml-4 mt-2 f1-font-bold mt-2">Highlight</h1> 
            <div class="query-page-selector-container mt-2" align="right">
                
                {% if highlights.has_previous %}
                    <a href="{% url 'media:highlight' %}?page={{ request.GET.page|add:-1 }}">        
                        <button class="query-page-selector-button mr-2 mt-2 f1-font-regular">Precedente</button>  
                    </a>
                {% else %}
                    <button class="query-page-selector-button mr-2 mt-2 f1-font-regular disabled-button">Precedente</button> 
                {% endif %}

                <h2 class="ml-auto mt-2 mr-2 f1-font-regular">[ </h2>
                {% if request.GET.page %}
                    <h2 class="ml-auto mt-2 mr-2 f1-font-regular">{{ request.GET.page }}</h2>
                {% else %}
                    <h2 class="ml-auto mt-2 mr-2 f1-font-regular">1</h2>
                {% endif %}
                <h2 class="ml-auto mt-2 mr-2 f1-font-regular"> ]</h2>
                
                {% if highlights.has_next %}
                    <a href="{% url 'media:highlight' %}?page={% if request.GET.page %}{{ request.GET.page|add:1 }}{% else %}2{% endif %}">
                        <button class="query-page-selector-button ml-auto mr-4 mt-2 f1-font-regular">Prossimo</button>    
                    </a>
                {% else %}
                    <button class="query-page-selector-button ml-auto mr-4 mt-2 f1-font-regular disabled-button">Prossimo</button> 
                {% endif %}

            </div>
        </div>
        <hr class="solid ml-4 mr-4 divisore"></hr>
        <div class="video-preview-container">

            {% for highlight in highlights %}
                <a href="{% url 'media:highlight_video' pk=highlight.id %}" class="card-video-preview video-preview ml-4 mr-4 mb-2">
                    <div>
                        <img class="video-highlight" src="{{highlight.preview}}">
                    </div>
                    <div class="mt-2">
                        <p class="highlight-name f1-font-regular">{{highlight.titolo}}</p>
                    </div>
                </a>
            {% endfor %}
        </div>
    </div>
    
{% endblock %}

F1/templates/media/homepage.html
{% extends 'base.html' %}
{% load crispy_forms_tags %} 
{% load static %}

{% block head %} 

	<link rel="stylesheet" type="text/css" href="{%static 'css/style_homepage.css'%}">
	<link rel="stylesheet" type="text/css" href="{%static 'css/style.css'%}">
	<script src="{%static 'js/homepage_carousel.js'%}"></script>

{% endblock %}

{% block title %}F1 - Homepage{% endblock %}

{% block content %}

	{% include 'media/homepage_user_auth_modal.html' %}

	<!-- Top content -->
	<div class="top-content mt-4">
		<div class="container-fluid">
			<div id="carousel-example" class="carousel slide" data-ride="carousel" data-interval="false">
				<div class="carousel-inner row w-75 mx-auto" role="listbox">
					{% for circuito in circuiti %}
						<div class="carousel-item col-12 col-sm-6 col-md-4 col-lg-3 {% if forloop.counter == 1 %}active{% endif %}">
							<a href="{% url 'info:circuito' pk=circuito.id %}">
								<img src="{{ circuito.preview }}" class="img-fluid d-block carousel-image" alt="img{{forloop.counter}}" {% if data > circuito.data_evento %}style="filter: grayscale(100%);"{% endif %}>
							</a>
						</div>
						{{first_for_counter|add:1}}
					{% endfor %}

				</div>
				<a class="carousel-control-prev" href="#carousel-example" role="button" data-slide="prev">
					<span class="carousel-control-prev-icon" aria-hidden="true"></span>
					<span class="sr-only">Previous</span>
				</a>
				<a class="carousel-control-next" href="#carousel-example" role="button" data-slide="next">
					<span class="carousel-control-next-icon" aria-hidden="true"></span>
					<span class="sr-only">Next</span>
				</a>
			</div>
		</div>
	</div>

	<!-- News -->
	<div id="container" class="text-white">
		<div id="news" class="card" style="overflow-x: hidden;">
			<h2 class="mx-auto f1-font-bold mt-2">NEWS</h2>

			{% for notizia in news %}
				<a href="{{ notizia.link_news }}" target="_blank">
					<hr class="solid ml-4 mr-4 divisore"></hr>
					<div class="article ml-4 mt-2 mb-2 container">
						<div class="row f1-border--top-right" style="max-width: 98%;">
							<div class="col-sm-5 immagine-news">
								<img src="{{ notizia.immagine }}">
							</div>
							<div class="col-sm-7 testo-news" align="center">
								<h4 id="news-title" class="f1-font-regular mb-4">{{ notizia.titolo }}</h4>
								<div class="data-news f1-font-regular">{{ notizia.data }}</div>
							</div>
						</div>
					</div>
				</a>
			{% endfor %}

			{% if user.utente %}
				{% for notizia in unfollowed_news %}
					<a href="{{ notizia.link_news }}" target="_blank">
						<hr class="solid ml-4 mr-4 divisore"></hr>
						<div class="article ml-4 mt-2 mb-2 container">
							<div class="row f1-border--top-right" style="max-width: 98%;">
								<div class="col-sm-5 immagine-news">
									<img src="{{ notizia.immagine }}">
								</div>
								<div class="col-sm-7 testo-news" align="center">
									<h4 id="news-title" class="f1-font-regular mb-4">{{ notizia.titolo }}</h4>
									<div class="data-news f1-font-regular">{{ notizia.data }}</div>
								</div>
							</div>
						</div>
					</a>
				{% endfor %}
			{% endif %}
		</div>
	
		<!-- Risultati ultima sessione -->
		<div id="risultati-ultima-sessione" class="background-profile card" style="">
			<h2 class="mx-auto f1-font-bold mt-2">Risultati {{ tipo_sessione }} - <a href="{% url 'info:circuito' pk=circuito_ultima_sessione.id %}" class="de-link">{{ nome_circuito }}</a></h2>
			<table class="risultati-ultima-sessione mt-3 ml-2 mr-2">
				<tr>
					<th class="white-cell f1-font-bold">POSIZIONE</th>
					<th class="white-cell f1-font-bold">PILOTA</th>
					<th class="white-cell f1-font-bold">MIGLIOR TEMPO</th>
				</tr>
				{% for partecipazione in partecipazioni %}
					<tr>
						<th class="white-cell f1-font-regular">{{ partecipazione.posizione }}</td>
						<th class="white-cell f1-font-regular"><a class="de-link" href="{% url 'info:pilota' pk=partecipazione.pilota.id %}">{{ partecipazione.pilota.nome }}</a></td>
						<th class="white-cell f1-font-regular">{{ partecipazione.miglior_tempo }}</td>
					</tr>
				{% endfor %}
			</table>
		</div>
	</div>
	
	
	




	<footer id="footer">
		<div id="footer-content">
			<a class="f1-font-regular" href="https://moodle.unimore.it/pluginfile.php/664168/mod_amanote/content/1/Progetti_esame.pdf" target="_blank">Traccia d'esame</a>
		</div>
	</footer>

{% endblock %}

F1/templates/media/homepage_user_auth_modal.html
{% block user_auth_modal %}
    {% if user.is_authenticated and "ok" in request.GET.login %}

        <div id="successo_login_modal" class="modal fade modalfont" tabindex="-1" role="dialog">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header modal-background">
                        <h5 class="modal-title">Benvenuto, {{ user.username }}!</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                <div class="modal-body modal-background" style="display: flex; justify-content: center; align-items: center;">
                    <p> La procedura di login è andata a buon fine </p>
                </div>
                    <div class="modal-footer modal-background" style="display: flex; justify-content: center;">
                        <button type="button" class="btn btn-info modal-button" data-dismiss="modal">Continua</button>
                    </div>
                </div>
            </div>
        </div> 

        <script>
        $(document).ready(function()
        {
            $("#successo_login_modal").modal('show');
        });
        </script>

    {% endif %}

    {% if not user.is_authenticated and "ok" in request.GET.logout %}

        <div id="successo_logout_modal" class="modal fade modalfont" tabindex="-1" role="dialog">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header modal-background">
                        <h5 class="modal-title">Alla prossima!</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                <div class="modal-body modal-background" style="display: flex; justify-content: center; align-items: center;">
                    <p> La procedura di logout è andata a buon fine </p>
                </div>
                    <div class="modal-footer modal-background" style="display: flex; justify-content: center;">
                        <button type="button" class="btn btn-info modal-button" data-dismiss="modal">Continua</button>
                    </div>
                </div>
            </div>
        </div> 

        <script>
        $(document).ready(function()
        {
            $("#successo_logout_modal").modal('show');
        });
        </script>

    {% endif %}

{% endblock%}

F1/templates/media/video_highlight.html
{% extends 'base.html' %}
{% load crispy_forms_tags %} 
{% load static %}

{% block head %} 

	<link rel="stylesheet" type="text/css" href="{%static 'css/style.css'%}">
    <link rel="stylesheet" type="text/css" href="{%static 'css/style_highlight.css'%}">

{% endblock %}

{% block title %}{{video.titolo}}{% endblock %}

{% block content %}

    <div class="highlight-container mt-4 ml-4 mr-4 mb-4 text-white">
        <div class="query-page-selector-container" align="right">
        <h1 class="ml-4 mt-1 f1-font-bold">{{video.titolo}}</h1> 
            <div class="query-page-selector-container" align="right">
                <h2 class="f1-font-bold mr-4 mt-3" style="text-align: right;">{{video.visualizzazioni}} visualizzazioni</h2>
                <a href="{% url 'media:highlight' %}?page=1">
                    <button class="query-page-selector-button mr-4 f1-font-regular mt-3">Torna agli Highlight</button>     
                </a>
            </div>
        </div>
        <hr class="solid ml-4 mr-4 divisore"></hr>
        <div class="video-preview-container" >

            <video controls class="video mb-3 mt-1">
                <source src="{{video.video}}" type="video/mp4" >
                Il tuo browser non supporta i video HTML.
            </video>

        </div>
    </div>
    
{% endblock %}