F1/F1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.contrib.auth import views as auth_views
from .views import UserCreateView, nothing_here, UserCreateSelection, CompanyCreateView, get_notifications

urlpatterns = [
    path('favicon.ico', RedirectView.as_view(url='/static/images/icons/favicon.ico')),
    path('admin/', admin.site.urls),
    path('nothing_here/', nothing_here, name='nothing_here'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register/', UserCreateSelection, name='register_selection'),
    path('register/utente/', UserCreateView.as_view(), name='register_user'),
    path('register/gestore/', CompanyCreateView.as_view(), name='register_company'),
    path('', include('media.urls')),
    path('', include('info.urls')),
    path('', include('store.urls')),
    path('query/notifications/', get_notifications, name='get_notifications'),
]

F1/info/urls.py
from .models import *
from django.urls import path
from info.views import follow, unfollow
from info.views import SessioniView, CircuitiView, ScuderieView, RisultatoSessioneView, TeamView, PilotaView, CircuitoView

app_name = 'info'

urlpatterns = [
    path('sessioni/', SessioniView.as_view(), name='sessioni'),
    path('sessioni/<pk>/<tipo_sessione>/', RisultatoSessioneView.as_view(), name='risultato_sessione'),
    path('circuiti/', CircuitiView.as_view(), name='circuiti'),
    path('circuiti/<pk>/', CircuitoView.as_view(), name='circuito'),
    path('scuderie/', ScuderieView.as_view(), name='scuderie' ),
    path('scuderie/team/<pk>/', TeamView.as_view(), name='team'),
    path('scuderie/team/<pk>/follow/', follow, name='follow'),
    path('scuderie/team/<pk>/unfollow/', unfollow, name='unfollow'),
    path('pilota/<pk>/', PilotaView.as_view(), name='pilota'),
]

F1/media/urls.py
from . import views
from .models import *
from django.urls import path
from media.views import HomePageView, HighlightPageView, VideoHighlightPageView

app_name = 'media'

urlpatterns = [
    path('', HomePageView.as_view(), name='homepage'),
    path('highlight/', HighlightPageView.as_view(), name='highlight'),
    path('highlight/<pk>/', VideoHighlightPageView.as_view(), name='highlight_video'),
]

F1/store/urls.py
from django.urls import path
from store.views import UserProfile, UtenteProfileDataChangeViewUpdate, StoreView, ProductView, CartView, GestoreProfileDataChangeViewUpdate, CreateTicketTypeView, CreateTicketInstanceView

app_name = 'store'

urlpatterns = [
    path('profile/', UserProfile, name='profile'),
    path('profile/modify_utente/<int:pk>/', UtenteProfileDataChangeViewUpdate.as_view(), name='modify_utente_update'),
    path('profile/modify_gestore/<int:pk>/', GestoreProfileDataChangeViewUpdate.as_view(), name='modify_gestore_update'),
    path('profile/create_ticket_type/', CreateTicketTypeView.as_view(), name='create_ticket_type'),
    path('profile/create_ticket_instance/', CreateTicketInstanceView.as_view(), name='create_ticket_instance'),
    path('store/', StoreView.as_view(), name='store'),
    path('store/product/<int:pk>/', ProductView.as_view(), name='product'),
    path('cart/', CartView.as_view(), name='cart'),
]

F1/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    {% load static %}

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{%static 'css/style.css'%}">

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/htmx.org@1.6.1"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

    <script src="{%static 'js/wallpaper.js'%}"></script>
    <script src="{%static 'js/navbar.js'%}"></script>

    {% block head %} {% endblock %}
    <title>{% block title %} {% endblock %}</title>

</head>


<body id='bg' style="background-image: url('{%static 'images/background.png'%}');">
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg">
        <!-- Icona notifiche, utente e carrello (collassato) -->
        <a class="navbar-brand d-lg-none text-white ml-2" href="{% url 'store:profile' %}">
          	<i class="fa fa-user"></i>
        </a>
        {% if not user.gestore_circuito %}
        <a class="navbar-brand d-lg-none text-white ml-1" href="{% url 'store:cart' %}">
          	<i class="fa fa-shopping-cart {% if user.is_authenticated and user.utente.carrello.istanze_biglietti.count > 0 %}notification-color blink{% endif %}"></i>
        </a>
        {% endif %}
        <a class="navbar-brand d-lg-none text-white ml-1" href="{% url 'store:profile' %}">
            <i class="fa fa-bell {% if user.is_authenticated and user.utente.notifiche %}notification-color blink{% elif user.is_authenticated and user.gestore_circuito.notifiche %}notification-color blink{% endif %}"></i>
        </a>

        <!-- Logo -->
        <a class="navbar-logo mx-auto" href="{% url 'media:homepage' %}">
          	<img src="{% static 'images/F1-Logo.png' %}" alt="Logo" width="90" height="60">
        </a>
        <!-- Menu a tre barre (collassato) -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation"
            aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation" id="toggler">
            <div class="container ml-auto" onclick="navbar_toggle(this)">
                <div class="bar1"></div>
                <div class="bar2"></div>
                <div class="bar3"></div>
            </div>
        </button>
        <!-- Link di navigazione (esteso) -->
        <div class="collapse navbar-collapse" id="navbarNav">
          	<ul class="navbar-nav mr-auto">
            	<li class="nav-item active">
              		<a class="nav-link f1-font-regular" href="{% url 'media:highlight' %}?page=1">Highlight</a>
            	</li>
            	<li class="nav-item">
              		<a class="nav-link f1-font-regular" href="{% url 'info:sessioni' %}">Sessioni</a>
            	</li>
            	<li class="nav-item">
              		<a class="nav-link f1-font-regular" href="{% url 'info:circuiti' %}">Circuiti</a>
            	</li>
            	<li class="nav-item">
              		<a class="nav-link f1-font-regular" href="{% url 'info:scuderie' %}">Scuderie</a>
            	</li>
            	<li class="nav-item">
                	<a class="nav-link f1-font-regular" href="{% url 'store:store' %}">Store</a>
            	</li>
                
          	</ul>
          	<!-- Icona notifiche, utente e carrello (esteso) -->
          	<ul class="navbar-nav">
                <ul class="navbar-nav">
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <div class="dropdown  f1-font-regular">
                                <a class="nav-link f1-font-regular mr-4" href="{% url 'store:profile' %}">Ciao, {{ user.username }}</a>
                                <div class="dropdown-content" align="left">
                                    <a href="{% url 'store:profile' %}">Profilo</a>
                                    <a href="{% url 'store:modify_utente_update' pk=user.pk %}">Modifica profilo</a>
                                    <a href="{% url 'logout' %}">Logout</a>
                                </div>
                            </div>
                        </li>
    
                        <li class="nav-item d-none d-lg-block">
                            <div class="dropdown">
                                <a class="nav-link mr-2 dropdown-toggle" id="profileDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <i id="bell" class="fa fa-bell {% if user.is_authenticated and user.utente.notifiche %}notification-color blink{% elif user.is_authenticated and user.gestore_circuito.notifiche %}notification-color blink{% endif %}"></i>
                                </a>
                                <div id="notification-div" class="dropdown-menu dropdown-menu-right outer-shadow" aria-labelledby="profileDropdown">
                                </div>
                            </div>
                        </li>
    
                    {% else %}
    
                        <a class="nav-link mr-2" href="{% url 'store:profile' %}">
                            <i class="fa fa-bell"></i>
                        </a>
        
                    {% endif %}
				<li class="nav-item d-none d-lg-block">
					<a class="nav-link mr-2" href="{% if user.is_superuser %}/admin/{% else %}{% url 'store:profile' %}{% endif %}">
						<i class="fa fa-user"></i>
					</a>
				</li>
                {% if not user.gestore_circuito %}
            	<li class="nav-item d-none d-lg-block">
              		<a class="nav-link mr-2" href="{% url 'store:cart' %}">
                		<i class="fa fa-shopping-cart {% if user.is_authenticated and user.utente.carrello.istanze_biglietti.count > 0 %}notification-color blink{% endif %}"></i>
              		</a>
            	</li>
                {% endif %}
          	</ul>
        </div>
    </nav>

    {% block content %}
    {% endblock %}

</body>
</html>

F1/templates/nothing_here.html
{% extends 'base.html' %}

{% load crispy_forms_tags %} 


{% block title %} F1 - Nothing here {{ form.user_group_name }} {% endblock %} 

{% block header1 %}
{% endblock %}

{% block content %} 


<div class="card f1-font-regular ml-4 mr-4 mt-4 mx-auto text-white" style="max-width: 90vw; max-height: 90vw; position: relative; overflow: hidden;">
    <div class="ml-4 mr-4 mt-2 mx-auto" style="display: flex;" align="center">
        <h1 class="ml-4 mt-2 f1-font-bold mt-2">Qui non c'è niente.</h1>
    </div>
        
    <div class="mx-auto" style="width: 73%;">
        <img class="mr-4 mb-4 " src="/static/images/gifs/nothing_here.gif" style="width: 100%; height: auto; display: block; margin: 0 auto;">
    </div>
</div>

{% endblock %}

{% block footer %} {% endblock %}