F1/F1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.contrib.auth import views as auth_views
from .views import UserCreateView, nothing_here, UserCreateSelection, CompanyCreateView, get_notifications

urlpatterns = [
    path('favicon.ico', RedirectView.as_view(url='/static/images/icons/favicon.ico')),
    path('admin/', admin.site.urls),
    path('nothing_here/', nothing_here, name='nothing_here'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register/', UserCreateSelection, name='register_selection'),
    path('register/utente/', UserCreateView.as_view(), name='register_user'),
    path('register/gestore/', CompanyCreateView.as_view(), name='register_company'),
    path('', include('media.urls')),
    path('', include('info.urls')),
    path('', include('store.urls')),
    path('query/notifications/', get_notifications, name='get_notifications'),
]

F1/info/urls.py
from .models import *
from django.urls import path
from info.views import follow, unfollow
from info.views import SessioniView, CircuitiView, ScuderieView, RisultatoSessioneView, TeamView, PilotaView, CircuitoView

app_name = 'info'

urlpatterns = [
    path('sessioni/', SessioniView.as_view(), name='sessioni'),
    path('sessioni/<pk>/<tipo_sessione>/', RisultatoSessioneView.as_view(), name='risultato_sessione'),
    path('circuiti/', CircuitiView.as_view(), name='circuiti'),
    path('circuiti/<pk>/', CircuitoView.as_view(), name='circuito'),
    path('scuderie/', ScuderieView.as_view(), name='scuderie' ),
    path('scuderie/team/<pk>/', TeamView.as_view(), name='team'),
    path('scuderie/team/<pk>/follow/', follow, name='follow'),
    path('scuderie/team/<pk>/unfollow/', unfollow, name='unfollow'),
    path('pilota/<pk>/', PilotaView.as_view(), name='pilota'),
]

F1/info/models.py
from django.db import models
from F1.validators import valida_non_negativi
from django_countries.fields import CountryField


class Scuderia(models.Model):
    nome = models.CharField(max_length=50, default='')
    nome_completo = models.CharField(max_length=50, default='')
    descrizione = models.CharField(max_length=10000, default='')
    modello_vettura = models.CharField(max_length=50, default='')
    modello_power_unit = models.CharField(max_length=50, default='')
    sede = models.CharField(max_length=100, default='')
    immagine_vettura = models.CharField(max_length=100)
    team_principal = models.CharField(max_length=100, default='')
    logo = models.CharField(max_length=100, default='')
    punti = models.PositiveIntegerField(default=0)
    immagine1 = models.CharField(max_length=100, default='', blank=True)
    immagine2 = models.CharField(max_length=100, default='', blank=True)
    campionati_vinti = models.PositiveIntegerField(default=0)

    class Meta:
        verbose_name_plural = 'Scuderie'


class Pilota(models.Model):
    nome = models.CharField(max_length=50)
    data = models.DateField()
    paese = CountryField(null=True, blank=True, default=None)
    foto_pilota = models.CharField(max_length=100, default='')
    foto_casco = models.CharField(max_length=100, default='')
    numero_gare = models.PositiveIntegerField(default=0)
    podi = models.PositiveIntegerField(default=0)
    campionati_vinti = models.PositiveIntegerField(default=0)
    numero_pilota = models.PositiveIntegerField(default=0)
    biografia = models.CharField(max_length=10000, default='')
    immagine = models.CharField(max_length=100, default='', blank=True)

    # Un pilota è ingaggiato da una sola scuderia
    scuderia = models.ForeignKey(Scuderia, on_delete=models.PROTECT, null=True, blank=True)

    class Meta:
        verbose_name_plural = 'Piloti'


class Circuito(models.Model):
    nome = models.CharField(max_length=50, default='')
    paese = CountryField(null=True, blank=True, default=None)
    capienza_persone = models.PositiveIntegerField()
    lunghezza = models.FloatField(validators=[valida_non_negativi])
    preview = models.CharField(max_length=100, default='')
    immagine_circuito = models.CharField(max_length=100, default='')
    immagine_mappa = models.CharField(max_length=100, default='')
    giro_veloce = models.CharField(max_length=100, default='')
    numero_giri = models.PositiveIntegerField()
    inaugurazione = models.DateField()
    storia = models.CharField(max_length=10000, default='')
    data_evento = models.DateField(null=True, blank=True, default=None)

    class Meta:
        verbose_name_plural = 'Circuiti'


class Sessione(models.Model):
    tipo = models.CharField(max_length=50)

    class Meta:
        verbose_name_plural = 'Sessioni'


class Partecipazione(models.Model):
    # null=True perché un pilota potrebbe non avere un tempo o partecipare a una determinata sessione
    miglior_tempo = models.CharField(max_length=100, null=True)  
    data = models.DateField(null=True)
    posizione = models.PositiveIntegerField(default=0)
    punti = models.PositiveIntegerField(default=0)

    # Una partecipazione si riferisce a una e una sola sessione
    sessione = models.ForeignKey(Sessione, on_delete=models.PROTECT, null=True, blank=True)

    # Una partecipazione si riferisce a uno e un solo circuito
    circuito = models.ForeignKey(Circuito, on_delete=models.PROTECT, null=True, blank=True)

    # Una partecipazione si riferisce a uno e un solo pilota
    pilota = models.ForeignKey(Pilota, on_delete=models.PROTECT, null=True, blank=True)

    class Meta:
        verbose_name_plural = 'Partecipazioni'

F1/info/views.py
from django.views.generic.list import ListView
from info.models import Circuito, Partecipazione, Scuderia, Sessione, Pilota

from media.forms import FormUtente
from store.models import Utente

from django.shortcuts import get_object_or_404, render
from django.http import JsonResponse
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required


class CircuitiView(ListView):
    '''Gestisce la pagina dei circuiti, fornendo i circuiti in ordine di data di evento'''
    model = Circuito
    template_name = 'info/menu_circuito.html' 

    def get_queryset(self):
        return self.model.objects.filter(nome="Circuit de Monaco")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        circuiti = Circuito.objects.all().order_by('-data_evento')
        context['circuiti'] = circuiti
        return context
    

class CircuitoView(ListView):
    '''Gestisce la pagina di un specifico circuito, fornendo le informazioni relative ad esso'''
    model = Circuito
    template_name = 'info/circuito.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        pk = self.kwargs.get('pk')
        circuito = Circuito.objects.get(pk=pk)

        context['circuito'] = circuito
        return context


class ScuderieView(ListView):
    '''Gestisce la pagina delle scuderie, fornendo le scuderie in ordine di punti'''
    model = Scuderia
    template_name = 'info/scuderia.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        scuderie = Scuderia.objects.all().order_by('-punti')
        piloti = Pilota.objects.all()

        context['piloti'] = piloti
        context['scuderie'] = scuderie
        
        return context
    

class TeamView(ListView):
    '''Gestisce la pagina di una specifica scuderia fornendo le informazioni relative e verifica se l'utente attuale segue la scuderia'''
    model = Scuderia
    template_name = 'info/team.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        pk = self.kwargs.get('pk')
        scuderia = Scuderia.objects.get(pk=pk)
        piloti = Pilota.objects.all()

        context['scuderia'] = scuderia
        context['piloti'] = piloti
        context['pk'] = pk

        try:
            context['follow'] = False
            if self.request.user.is_authenticated:
                utente = Utente.objects.get(user=self.request.user)
                if scuderia in utente.follow.all():
                    context['follow'] = True
                    
        except Utente.DoesNotExist:
            return context
        
        return context
    

class PilotaView(ListView):
    '''Gestisce la pagina di un specifico pilota, fornendo le informazioni relative ad esso'''
    model = Pilota
    template_name = 'info/pilota.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        pk = self.kwargs.get('pk')

        pilota = Pilota.objects.get(pk=pk)

        context['pilota'] = pilota
        return context



class SessioniView(ListView):
    '''Gestisce la pagina delle sessioni, mostrando le sessioni in ordine di data'''
    model = Partecipazione
    template_name = 'info/sessioni.html' 

    def get_context_data(self):
        context = super().get_context_data()

        circuiti = Circuito.objects.all()
        context['circuiti'] = circuiti

        partecipazioni = Partecipazione.objects.filter(posizione=1, sessione__tipo='gara').order_by('-data')
        context['partecipazioni'] = partecipazioni
        
        return context
    

class RisultatoSessioneView(ListView):
    '''Gestisce la pagina dei risultati di una specifica sessione, fornendo le informazioni relative alle partecipazioni di ogni pilota'''
    model = Partecipazione
    template_name = 'info/risultato_sessione.html' 
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data()

        pk = self.kwargs.get('pk')
        tipo_sessione = self.kwargs.get('tipo_sessione')
        partecipazioni = Partecipazione.objects.filter(circuito__pk=pk, sessione__tipo=tipo_sessione).order_by('posizione')
        sessioni_effettuate = Partecipazione.objects.filter(circuito__pk=pk).values_list('sessione__tipo', flat=True).distinct()
        
        context['partecipazioni'] = partecipazioni
        context['sessioni_effettuate'] = sessioni_effettuate
        context['pk'] = pk
        
        return context

@login_required
def follow(request, **kwargs):
    '''
    Aggiunge una scuderia alla lista dei preferiti dell'utente corrente e, se l'utente non è autenticato, 
    viene reindirizzato alla pagina di login.
    Valido solamente per gli utenti -> nel caso in cui un gestore provi ad accedere a questa view,
    verrebbe reindirizzato alla pagina della scuderia senza alcuna modifica al suo stato
    '''
    pk = kwargs.get('pk')
    if request.user.is_authenticated:
        try:
            utente = Utente.objects.get(user=request.user)
            scuderia = Scuderia.objects.get(pk=pk)

            if scuderia:
                utente.follow.add(scuderia)
                utente.save()
        except Utente.DoesNotExist:
            return redirect('info:team', pk=pk)

    return redirect('info:team', pk=pk)

@login_required
def unfollow(request, **kwargs):
    '''
    Rimuove una scuderia alla lista dei preferiti dell'utente corrente, e se l'utente non è autenticato,
    viene reindirizzato alla pagina di login.
    Valido solamente per gli utenti -> nel caso in cui un gestore provi ad accedere a questa view,
    verrebbe reindirizzato alla pagina della scuderia senza alcuna modifica al suo stato
    '''
    pk = kwargs.get('pk')
    if request.user.is_authenticated:
        try:
            utente = Utente.objects.get(user=request.user)
            scuderia = Scuderia.objects.get(pk=pk)

            if scuderia:
                utente.follow.remove(scuderia)
                utente.save()
        except Utente.DoesNotExist:
            return redirect('info:team', pk=pk)

    return redirect('info:team', pk=pk)

F1/templates/info/circuito.html
{% extends 'base.html' %}
{% load crispy_forms_tags %} 
{% load static %}

{% block head %} 

    <link rel="stylesheet" type="text/css" href="{%static 'css/style_circuito.css'%}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{%static 'css/style_highlight.css'%}">
    <link rel="stylesheet" type="text/css" href="{%static 'css/style.css'%}">

{% endblock %}

{% block title %}F1 - Circuito{% endblock %}

{% block content %}

    <!-- Hero -->
    <div class="p-5 text-center bg-image rounded-3" id="hero-img" style="
            background-image: url('{{ circuito.immagine_circuito }}');
            height: 47%; brightness: 70%;">
        <div class="mask">
            <div class="d-flex justify-content-center align-items-center h-100">
            <div class="text-white f1-center">
                <h1 class="margin-m f1-font" style="text-transform:uppercase">{{ circuito.paese.name }}</h1>
                <h2 class="margin-i"><img src="{% static 'images/circuits/2023.png' %}" width="200" height="70"></h2>
            </div>
            </div>
        </div>
    </div>

    <!-- titolo Circuito-->
    <div class="container mt-4 mb-4" id="hub">

        <div class="row">
            <div class="col-xl-6 col-lg-10 col-md-10 col-12">
                <p class="f1-font-r text-white">FORMULA 1 GRAND PRIX DE {{ circuito.paese.name }} 2023</p>
            </div>
            <div class="col-xl-6 col-lg-10 col-md-10 col-12" style="text-align: right;">
                <a href="{% url 'info:circuiti' %}" class="mt-2">
                    <button class="query-page-selector-button mr-2 f1-font-regular">Torna ai Circuiti</button>
                </a>
            </div>
        </div>

        <fieldset class="f1-border--top-right">
            <legend class="f1-font-leg">
                <span class="text-white">{{ circuito.nome }}</span>
            </legend>
                <div class="row">
                    <div class="col-xl-8 col-lg-10 col-md-10 col-12">
                        <p class="f1-font-r text-white"><img src="{{ circuito.immagine_mappa }}" id="img-p"></p>
                    </div>
                    <div class="col-xl-4 col-lg-10 col-md-10 col-12 text-white ml-auto margin-top" >
                        <div class="row"> 
                            <div class="col-lg-8 col-xl-12">
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="f1-stat">
                                            <p class="misc--label">Capienza</p>
                                            <p class="f1-bold-stat">{{ circuito.capienza_persone }}</p>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="f1-stat">
                                            <p class="misc--label">Lunghezza</p>
                                            <p class="f1-bold-stat">{{ circuito.lunghezza }}<span class="misc--label"> km</span></p>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="f1-stat">
                                            <p class="misc--label">Numero giri</p>
                                            <p class="f1-bold-stat">{{ circuito.numero_giri }}</p>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="f1-stat">
                                            <p class="misc--label">Giro veloce</p>
                                            <p class="f1-bold-stat">{{ circuito.giro_veloce }}<span class="misc--label"></span></p>
                                        </div>
                                    </div>
                                    <div class="col-12">
                                        <div class="f1-stat ">
                                            <p class="misc--label">Inaugurazione</p>
                                            <p class="f1-bold-stat">{{ circuito.inaugurazione }}</p>
                                            
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </fieldset>

            <div class="row">
                <div class="col-md-8">
                    <fieldset class="font-story text-white">
                        <legend class="leg-story">
                            <span class="text-white">Storia</span>
                        </legend>
                        {{ circuito.storia }}
                    </fieldset>
                </div>
            </div>
    </div>

{% endblock %}

F1/templates/info/menu_circuito.html
{% extends 'base.html' %}
{% load crispy_forms_tags %} 
{% load static %}

{% block head %} 

	<link rel="stylesheet" type="text/css" href="{%static 'css/style.css'%}">
    <link rel="stylesheet" type="text/css" href="{%static 'css/style_circuito.css'%}">

{% endblock %}

{% block title %}F1 - Circuiti{% endblock %}

{% block content %}

<div class="cir-container mt-4 ml-4 mr-4 mb-4 text-white">
    <div class="query-page-selector-container" align="right">
        <h1 class="ml-4 mt-2 f1-font-bold mt-2">Circuiti</h1> 
    </div>
    <hr class="solid ml-4 mr-4 divisore"></hr>
    <div class="cir-preview-container">
        
        {% for circuito in circuiti %}
            <a href="{% url 'info:circuito' pk=circuito.id %}" class="card-cir-preview cir-preview ml-4 mr-4 mb-2">
                <div>
                    <img class="circuit" src="{{circuito.preview}}" width="1920" height="1080">
                    <i class="icon icon-play cir-icon"></i>
                    
                </div>
                <div class="mt-2">
                    <p class="cir-name f1-font-regular">{{circuito.nome}}</p>
                </div>
            </a>
        {% endfor %}
    </div>
</div>
    
{% endblock %}

F1/templates/info/risultato_sessione.html
{% extends 'base.html' %}
{% load crispy_forms_tags %} 
{% load static %}

{% block head %} 

	<link rel="stylesheet" type="text/css" href="{%static 'css/style.css'%}">
    <link rel="stylesheet" type="text/css" href="{%static 'css/style_sessioni.css'%}">

{% endblock %}

{% block title %}F1 - Sessioni{% endblock %}

{% block content %}

<div class="sessioni-container mt-4 ml-4 mr-4 mb-4 text-white">
    <div class="query-page-selector-container" align="right">
        <h1 class="ml-4 mt-2 f1-font-bold mt-2">Risultati {{partecipazioni.0.sessione.tipo}} - {{partecipazioni.0.circuito.nome}}</h1> 
        <div class="query-page-selector-container mr-3" align="right">
            
            <div class="dropdown f1-font-regular">
                <button class="query-page-selector-button mt-3 mr-3">Sessioni disputate</button>
                <div class="dropdown-content" align="left">
                    
                    {% for sessione_effettuata in sessioni_effettuate %}
                        <a href="{% url 'info:risultato_sessione' pk=pk tipo_sessione=sessione_effettuata %}">{{ sessione_effettuata }}</a>
                    {% endfor %}

                </div>
            </div>

            <a href="{% url 'info:sessioni' %}">
                <button class="query-page-selector-button f1-font-regular mt-3 mr-2">Torna alle sessioni</button>     
            </a>
        </div>
    </div>
    <hr class="solid ml-4 mr-4 divisore"></hr>

    <!-- Tabella sessioni -->
    <div id="sessioni-table-div" class="card ml-4 mr-4 mb-4 mt-4">
        <table class="risultati-sessioni">
            <tr>
                <th class="sessioni-cell f1-font-bold"><h3>POSIZIONE</h3></th>
                <th class="sessioni-cell f1-font-bold"><h3>PILOTA<h3></th>
                <th class="sessioni-cell f1-font-bold"><h3>SCUDERIA</h3></th>
                {% if partecipazioni.0.sessione.tipo != "qualifiche" %}
                    <th class="sessioni-cell f1-font-bold"><h3>PUNTI</h3></th>
                {% endif %}
                <th class="sessioni-cell f1-font-bold"><h3>GIRO VELOCE</h3></th>
            </tr>
            {% for partecipazione in partecipazioni %}
                <tr>
                    <th class="sessioni-cell f1-font-regular">{{ partecipazione.posizione }}</td>
                    <th class="sessioni-cell f1-font-regular"><a class="de-link" href="{% url 'info:pilota' pk=partecipazione.pilota.id %}">{{ partecipazione.pilota.nome }}</a></td>
                    <th class="sessioni-cell f1-font-regular"><a class="de-link" href="{% url 'info:team' pk=partecipazione.pilota.scuderia.id %}">{{ partecipazione.pilota.scuderia.nome }}</a></td>
                    {% if partecipazione.sessione.tipo != "qualifiche" %}
                        <th class="sessioni-cell f1-font-regular">{{ partecipazione.punti }}</td>
                    {% endif %}
                    <th class="sessioni-cell f1-font-regular">{{ partecipazione.miglior_tempo }}</td>
                </tr>
            {% endfor %}
        </table>
    </div>  
</div>
    
{% endblock %}

F1/templates/info/sessioni.html
{% extends 'base.html' %}
{% load crispy_forms_tags %} 
{% load static %}

{% block head %} 

	<link rel="stylesheet" type="text/css" href="{%static 'css/style.css'%}">
    <link rel="stylesheet" type="text/css" href="{%static 'css/style_sessioni.css'%}">

{% endblock %}

{% block title %}F1 - Sessioni{% endblock %}

{% block content %}

<div class="sessioni-container mt-4 ml-4 mr-4 mb-4 text-white">
    <div class="query-page-selector-container" align="right">
    <h1 class="ml-4 mt-2 f1-font-bold mt-2">Sessioni</h1> 
        <div class="query-page-selector-container mt-2" align="right">
        </div>
    </div>
    <hr class="solid ml-4 mr-4 divisore"></hr>
    <!-- Tabella sessioni -->
    <div id="sessioni-table-div" class="card ml-4 mr-4 mb-4 mt-4">
        <table class="risultati-sessioni">
            <tr>
                <th class="sessioni-cell f1-font-bold"><h3>GRAN PREMIO</h3></th>
                <th class="sessioni-cell f1-font-bold"><h3>DATA<h3></th>
                <th class="sessioni-cell f1-font-bold"><h3>VINCITORE</h3></th>
                <th class="sessioni-cell f1-font-bold"><h3>SCUDERIA</h3></th>
                <th class="sessioni-cell f1-font-bold"><h3>GIRI</h3></th>
            </tr>
            {% for partecipazione in partecipazioni %}
                <tr>
                    <th class="sessioni-cell f1-font-regular">
                        <a class="link-sessione" href="{% url 'info:risultato_sessione' pk=partecipazione.circuito.id tipo_sessione=partecipazione.sessione.tipo %}">
                            {{ partecipazione.circuito.nome }}
                        </a>
                    </td>
                    
                    <th class="sessioni-cell f1-font-regular">{{ partecipazione.data }}</td>
                    <th class="sessioni-cell f1-font-regular"><a class="de-link" href="{% url 'info:pilota' pk=partecipazione.pilota.id %}">{{ partecipazione.pilota.nome }}</a></td>
                    <th class="sessioni-cell f1-font-regular"><a class="de-link" href="{% url 'info:team' pk=partecipazione.pilota.scuderia.id %}">{{ partecipazione.pilota.scuderia.nome }}</a></td>
                    <th class="sessioni-cell f1-font-regular">{{ partecipazione.circuito.numero_giri }}</td>
                </tr>
            {% endfor %}

        </table>
    </div>  
</div>
    
{% endblock %}

F1/templates/info/team.html
{% extends 'base.html' %}
{% load crispy_forms_tags %} 
{% load static %}

{% block head %} 

	<link rel="stylesheet" type="text/css" href="{%static 'css/style.css'%}">
    <link rel="stylesheet" type="text/css" href="{%static 'css/style_team.css'%}">
    
{% endblock %}

{% block title %}F1 - {{scuderia.nome}}{% endblock %}

{% block content %}

    <div class="container-title mt-4 mb-4 mx-auto">
        <div class="row">
            <a class="font-title text-white mt-4">{{scuderia.nome}}</a>

            {% if user.is_authenticated %}
                {% if user.utente %}
                    {% if follow %}
                        <a href="{% url 'info:unfollow' pk=pk %}">
                            <button class="fa fa-heart inverted-follow-button"></button>
                        </a>
                    {% else %}
                        <a href="{% url 'info:follow' pk=pk %}">
                            <button class="fa fa-heart follow-button"></button>
                        </a>
                    {% endif %} 
                {% endif %} 
            {% endif %} 
        </div>

    </div>

    <div class="container-team mt-4 mb-4 mx-auto">
        <div class="row">

            <div class="col-6 mt-4 mb-4">
                <h2 class="col-6" style="text-align: left;"><img src="{{scuderia.logo}}" width="500px" height="300px" style="border-radius: 10px;"></h2>

                <div class="row padu">
                    <div class="col-6 padl">
                        <p class="font-textb text-white" style="text-align: left;">Nome completo team</p>
                    </div>
                    <div class="col-6">
                        <p class="font-textr text-white" style="text-align: left;">{{ scuderia.nome_completo }}</p>
                    </div>
                </div>

                <div class="row">
                    <div class="col-6 padl">
                        <p class="font-textb text-white" style="text-align: left;">Sede</p>
                    </div>
                    <div class="col-6">
                        <p class="font-textr text-white" style="text-align: left;">{{ scuderia.sede }}</p>
                    </div>
                </div>

                <div class="row">
                    <div class="col-6 padl">
                        <p class="font-textb text-white" style="text-align: left;">Team Principal</p>
                    </div>
                    <div class="col-6">
                        <p class="font-textr text-white" style="text-align: left;">{{scuderia.team_principal}}</p>
                    </div>
                </div>

                <div class="row">
                    <div class="col-6 padl">
                        <p class="font-textb text-white" style="text-align: left;">Modello vettura</p>
                    </div>
                    <div class="col-6">
                        <p class="font-textr text-white" style="text-align: left;">{{ scuderia.modello_vettura }}</p>
                    </div>
                </div>

                <div class="row">
                    <div class="col-6 padl">
                        <p class="font-textb text-white" style="text-align: left;">Power Unit</p>
                    </div>
                    <div class="col-6">
                        <p class="font-textr text-white" style="text-align: left;">{{scuderia.modello_power_unit}}</p>
                    </div>
                </div>

                <div class="row">
                    <div class="col-6 padl">
                        <p class="font-textb text-white" style="text-align: left;">Campionati vinti</p>
                    </div>
                    <div class="col-6">
                        <p class="font-textr text-white" style="text-align: left;">{{scuderia.campionati_vinti}}</p>
                    </div>
                </div>
            </div>

            <div class="col-6 mt-4 mb-4">
                <div class="row" id="alt">
                    {% for pilota in piloti %}
                        {% if pilota.scuderia == scuderia %}
                            <div class="col-6 padlf driver">
                                <a href="{% url 'info:pilota' pk=pilota.id %}" class="mt-2">
                                    <figure class="driver">
                                                <p class="driver-img" style="background-image: url('{{pilota.foto_pilota}}');" >
                                            <figcaption>
                                                <div class="font-num text-white padl">
                                                    <span>{{pilota.numero_pilota}}</span>
                                                </div>
                                                <h1 class="font-textr text-white padl">
                                                    {{pilota.nome}}
                                                </h1>
                                            </figcaption>
                                    </figure>
                                </a>
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
        </div>

        <div class="row">
            <div id="carouselExampleIndicators" class="carousel slide w-100" data-ride="carousel">
                <ol class="carousel-indicators">
                <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                </ol>
                <div class="carousel-inner">
                <div class="carousel-item active">
                    <img class="d-block w-100" src="{{scuderia.immagine1}}" alt="First slide">
                </div>
                <div class="carousel-item">
                    <img class="d-block w-100" src="{{scuderia.immagine2}}" alt="Second slide">
                </div>
                </div>
                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
                </a>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <fieldset class="font-story text-white">
                    <legend class="leg-story">
                        <span class="text-white">Descrizione</span>
                    </legend>
                    <div class="pads font-s">
                        {{scuderia.descrizione}}
                    </div>
        </div>
    </div>
    
{% endblock %}
    